application-name: @project.artifactId@
application-description: @project.description@
application-version: @project.version@

server:
  port: 8080
  servlet:
    context-path: /item-storage/api/v${item.api.version}

spring:
  application:
    name: item-storage
  boot:
    admin:
      client:
        url: http://localhost:9090
  datasource:
    url: "jdbc:h2:mem:testdb"
  h2:
    console:
      enabled: true
      path: /h2-console

springdoc:
  api-docs:
    path: "/api-docs"
  swagger-ui:
    path: "/"

item:
  api:
    version: 1

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
